name: Leo Hello SecDevOps
on: 
  push:
    branches: [ "test" ]
  workflow_dispatch:

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    name: Run a shell command and print some text
    steps:  
      - name: Echo a string
        run: echo "Hello SecDevOps team"
